# Generated by Django 3.0.6 on 2020-05-20 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HKmanager', '0002_auto_20200519_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='HKmanager.block'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='HKmanager.status'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='HKmanager.task'),
        ),
    ]
