# Generated by Django 3.0.6 on 2020-05-21 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HKmanager', '0004_bathroom_bedroom_corridor_ensuite_kitchen_livingroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='numberOfRooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='villages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='rooms',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='HKmanager.numberOfRooms'),
        ),
    ]
