# Generated by Django 3.0.6 on 2020-05-22 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HKmanager', '0005_auto_20200521_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedroom',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HKmanager.apartment'),
        ),
    ]
