# Generated by Django 3.0.6 on 2020-05-22 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HKmanager', '0007_auto_20200522_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bedroom',
            name='apartment',
        ),
        migrations.AddField(
            model_name='bedroom',
            name='apartment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='HKmanager.apartment'),
        ),
    ]
