# Generated by Django 3.0.6 on 2020-05-24 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HKmanager', '0009_bedroom_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='tasksBedroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='tasksCorridor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='tasksKitchen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='taskslivingRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='ensuite',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HKmanager.apartment'),
        ),
        migrations.CreateModel(
            name='livingRoomCheckList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked', models.BooleanField(default=False)),
                ('livingroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HKmanager.livingRoom')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='HKmanager.taskslivingRoom')),
            ],
        ),
        migrations.CreateModel(
            name='kitchenCheckList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked', models.BooleanField(default=False)),
                ('kitchen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HKmanager.kitchen')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='HKmanager.tasksKitchen')),
            ],
        ),
        migrations.CreateModel(
            name='corridorCheckList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked', models.BooleanField(default=False)),
                ('corrior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HKmanager.corridor')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='HKmanager.tasksCorridor')),
            ],
        ),
        migrations.CreateModel(
            name='bedroomCheckList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked', models.BooleanField(default=False)),
                ('corrior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HKmanager.bedroom')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='HKmanager.tasksBedroom')),
            ],
        ),
    ]
