# Generated by Django 3.0.6 on 2020-05-24 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HKmanager', '0010_auto_20200524_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='tasksEnsuite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='bedroomchecklist',
            old_name='corrior',
            new_name='bedroom',
        ),
        migrations.RenameField(
            model_name='corridorchecklist',
            old_name='corrior',
            new_name='corridor',
        ),
        migrations.CreateModel(
            name='ensuiteCheckList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked', models.BooleanField(default=False)),
                ('bedroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HKmanager.bedroom')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='HKmanager.tasksEnsuite')),
            ],
        ),
    ]
