# Generated by Django 3.0.6 on 2020-05-30 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HKmanager', '0011_auto_20200524_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ensuitechecklist',
            name='bedroom',
        ),
        migrations.AddField(
            model_name='ensuitechecklist',
            name='ensuite',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='HKmanager.ensuite'),
        ),
    ]
