# Generated by Django 3.0.6 on 2020-06-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HKmanager', '0013_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedroomchecklist',
            name='callback',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='corridorchecklist',
            name='callback',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ensuitechecklist',
            name='callback',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kitchenchecklist',
            name='callback',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livingroomchecklist',
            name='callback',
            field=models.BooleanField(default=False),
        ),
    ]
